Bugfix: prevent config.products.omitVariantFields being mutated
vuestorefront/vue-storefront-1 pull request #497
Opened 2021-10-13 12:06 UTC by didkan

### Related Issues

closes #496

### Short Description of the PR
This bug mutates a config value so it affects more products than intended. Read more in issue linked above.

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/vuestorefront/vue-storefront-1/blob/master/CHANGELOG.md)) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/vuestorefront/vue-storefront-1/blob/master/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/vuestorefront/vue-storefront-1/blob/master/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/vuestorefront/vue-storefront-1/blob/master/CONTRIBUTING.md)

2021-12-17 14:47 UTC, Fifciu requested changes
Good job. Please resolve the conflict

2021-12-20 08:54 UTC, didkan commented
@Fifciu Conflict resolved.

2021-12-22 10:36 UTC, Fifciu approved these changes

2021-12-22 10:36 UTC, Fifciu commented
Thank you!

2021-12-22 10:37 UTC, merged